# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/cugxy/Documents/git/LiGlobal/LiGlobal/tool/video_tool/ui/cut_video.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(641, 490)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.stackedWidget = QtWidgets.QStackedWidget(Dialog)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout = QtWidgets.QGridLayout(self.page)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.page)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.edit_video_path = QtWidgets.QLineEdit(self.page)
        self.edit_video_path.setObjectName("edit_video_path")
        self.horizontalLayout_2.addWidget(self.edit_video_path)
        self.btn_video_path = QtWidgets.QPushButton(self.page)
        self.btn_video_path.setObjectName("btn_video_path")
        self.horizontalLayout_2.addWidget(self.btn_video_path)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.edit_time = QtWidgets.QLineEdit(self.page)
        self.edit_time.setObjectName("edit_time")
        self.horizontalLayout_3.addWidget(self.edit_time)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.btn_next = QtWidgets.QPushButton(self.page)
        self.btn_next.setObjectName("btn_next")
        self.horizontalLayout_4.addWidget(self.btn_next)
        self.btn_get_img = QtWidgets.QPushButton(self.page)
        self.btn_get_img.setObjectName("btn_get_img")
        self.horizontalLayout_4.addWidget(self.btn_get_img)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_8 = QtWidgets.QLabel(self.page_2)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.groupBox = QtWidgets.QGroupBox(self.page_2)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.edit_x0 = QtWidgets.QLineEdit(self.groupBox)
        self.edit_x0.setObjectName("edit_x0")
        self.gridLayout_2.addWidget(self.edit_x0, 0, 1, 1, 1)
        self.edit_y0 = QtWidgets.QLineEdit(self.groupBox)
        self.edit_y0.setObjectName("edit_y0")
        self.gridLayout_2.addWidget(self.edit_y0, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.edit_x1 = QtWidgets.QLineEdit(self.groupBox)
        self.edit_x1.setObjectName("edit_x1")
        self.gridLayout_2.addWidget(self.edit_x1, 1, 1, 1, 1)
        self.edit_y1 = QtWidgets.QLineEdit(self.groupBox)
        self.edit_y1.setObjectName("edit_y1")
        self.gridLayout_2.addWidget(self.edit_y1, 1, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.page_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 0, 1, 1)
        self.edit_error_size = QtWidgets.QLineEdit(self.groupBox_2)
        self.edit_error_size.setObjectName("edit_error_size")
        self.gridLayout_3.addWidget(self.edit_error_size, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 1, 0, 1, 1)
        self.edit_error_time = QtWidgets.QLineEdit(self.groupBox_2)
        self.edit_error_time.setObjectName("edit_error_time")
        self.gridLayout_3.addWidget(self.edit_error_time, 1, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.page_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9)
        self.edit_out_path = QtWidgets.QLineEdit(self.groupBox_3)
        self.edit_out_path.setObjectName("edit_out_path")
        self.horizontalLayout.addWidget(self.edit_out_path)
        self.btn_out_path = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_out_path.setObjectName("btn_out_path")
        self.horizontalLayout.addWidget(self.btn_out_path)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.btn_prv = QtWidgets.QPushButton(self.page_2)
        self.btn_prv.setObjectName("btn_prv")
        self.horizontalLayout_5.addWidget(self.btn_prv)
        self.btn_cut = QtWidgets.QPushButton(self.page_2)
        self.btn_cut.setObjectName("btn_cut")
        self.horizontalLayout_5.addWidget(self.btn_cut)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout_4.addWidget(self.stackedWidget)
        self.text_log = QtWidgets.QTextBrowser(Dialog)
        self.text_log.setObjectName("text_log")
        self.verticalLayout_4.addWidget(self.text_log)

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3.setText(_translate("Dialog", "截取视频图片"))
        self.label.setText(_translate("Dialog", "视频文件："))
        self.btn_video_path.setText(_translate("Dialog", "..."))
        self.label_2.setText(_translate("Dialog", "时       间："))
        self.btn_next.setText(_translate("Dialog", "下一步"))
        self.btn_get_img.setText(_translate("Dialog", "处理"))
        self.label_8.setText(_translate("Dialog", "裁剪视频"))
        self.groupBox.setTitle(_translate("Dialog", "样本"))
        self.label_4.setText(_translate("Dialog", "左上角坐标："))
        self.label_5.setText(_translate("Dialog", "右下角坐标："))
        self.groupBox_2.setTitle(_translate("Dialog", "误差参数"))
        self.label_6.setText(_translate("Dialog", "误差参数："))
        self.label_7.setText(_translate("Dialog", "时间参数："))
        self.groupBox_3.setTitle(_translate("Dialog", "输出"))
        self.label_9.setText(_translate("Dialog", "输出目录："))
        self.btn_out_path.setText(_translate("Dialog", "..."))
        self.btn_prv.setText(_translate("Dialog", "上一步"))
        self.btn_cut.setText(_translate("Dialog", "处理"))

